export const STATUS_OPTS = [
  "All Statuses",
  "Approved",
  "Draft",
  "Pending",
  "Not approved",
];

export const TYPE_OPTS = [
  "All Types",
  "Fraud",
  "PIDPI",
  "CVC",
  "Whistle blower",
  "Misconduct",
  "NPA",
];

export const SOURCE_OPTS = [
  "All Sources",
  "Internal",
  "Customer",
  "RBI",
  "Agency",
  "FRMD",
  "Whistleblower",
];

export const mockDashboard = {
  approvalList: [
    {
      id: "1",
      referenceNumber: "HO/VIG/2024/001",
      typeOfComplaint: "Fraud",
      sourceOfComplaint: "Internal",
      status: "Pending",
      refNo: "HO/VIG/2024/001",
      date: "2024-01-15",
      nameOfOfficial: "John Doe",
      designation: "Branch Manager",
      address: "123 Main Street",
      state: "Maharashtra",
      email: "john.doe@bankofindia.co.in",
      mobile: "9876543210",
      natureOfComplaint: "Financial irregularities",
      allegationBrief: "Misappropriation of funds",
      amountInvolved: "500000",
      probableLoss: "250000",
      isFormApproved: "Pending",
      dateOfApproval: "",
      attachDocument: null,
      // New fields for expanded form
      nameOfAccount: "ABC Corporation",
      dateOfComplaint: "2024-01-10",
      letterReferenceNo: "REF/LET/2024/001",
      dateOfDeclarationFraud: "",
      fraudComplaintResignationNo: "FCR/2024/001",
      dateOfReceipt: "2024-01-12",
      complainantName: "John Doe",
      pin: "400001",
      kycLetter1: "Sent on 2024-01-05",
      kycLetter2: "Sent on 2024-01-12",
      replyReceived: "Received on 2024-01-20",
      kycEstablishment: "Verified",
      kycNo: "KYC123456",
      branchOffice: "Main Branch Mumbai",
      zoneNbg: "West Zone",
      officialInvolvement: "Yes",
      allegationDetails: "Misappropriation of funds from customer accounts",
      modusOperandi: "Created fake accounts and transferred funds",
      officerName: "Rajesh Kumar",
      officerPf: "PF12345",
      presentPosting: "Mumbai Regional Office",
      proposedCompletionDate: "2024-03-15",
      deptObservation: "Need thorough investigation",
      cvoComments: "Approve with additional documentation",
      scopeRows: [
        { sno: 1, particulars: "Review financial records" },
        { sno: 2, particulars: "Interview staff members" },
        { sno: 3, particulars: "Audit transaction logs" },
      ],
    },
    {
      id: "2",
      referenceNumber: "HO/VIG/2024/002",
      typeOfComplaint: "PIDPI",
      sourceOfComplaint: "Customer",
      status: "Approved",
      refNo: "HO/VIG/2024/002",
      date: "2024-01-10",
      nameOfOfficial: "Jane Smith",
      designation: "Assistant Manager",
      address: "456 Park Avenue",
      state: "Gujarat",
      email: "jane.smith@bankofindia.co.in",
      mobile: "9876543211",
      natureOfComplaint: "Harassment",
      allegationBrief: "Verbal abuse by staff",
      amountInvolved: "0",
      probableLoss: "0",
      isFormApproved: "Yes",
      dateOfApproval: "2024-01-20",
      attachDocument: null,
      nameOfAccount: "XYZ Enterprises",
      dateOfComplaint: "2024-01-05",
      letterReferenceNo: "REF/LET/2024/002",
      dateOfDeclarationFraud: "",
      fraudComplaintResignationNo: "FCR/2024/002",
      dateOfReceipt: "2024-01-07",
      complainantName: "Jane Smith",
      pin: "380001",
      kycLetter1: "Sent on 2024-01-06",
      kycLetter2: "Sent on 2024-01-13",
      replyReceived: "Received on 2024-01-18",
      kycEstablishment: "Verified",
      kycNo: "KYC789012",
      branchOffice: "Ahmedabad Branch",
      zoneNbg: "West Zone",
      officialInvolvement: "Yes",
      allegationDetails: "Harassment of customer for loan recovery",
      modusOperandi: "Used abusive language and threats",
      officerName: "Priya Sharma",
      officerPf: "PF67890",
      presentPosting: "Ahmedabad Zonal Office",
      proposedCompletionDate: "2024-02-28",
      deptObservation: "Customer complaint verified",
      cvoComments: "Take disciplinary action",
      scopeRows: [
        { sno: 1, particulars: "Review CCTV footage" },
        { sno: 2, particulars: "Customer statement recording" },
      ],
    },
    {
      id: "3",
      referenceNumber: "HO/VIG/2024/003",
      typeOfComplaint: "CVC",
      sourceOfComplaint: "RBI",
      status: "Draft",
      refNo: "HO/VIG/2024/003",
      date: "2024-01-18",
      nameOfOfficial: "Robert Johnson",
      designation: "Chief Manager",
      address: "789 Business Park",
      state: "Delhi",
      email: "robert.johnson@bankofindia.co.in",
      mobile: "9876543212",
      natureOfComplaint: "Non-compliance",
      allegationBrief: "RBI guidelines violation",
      amountInvolved: "1000000",
      probableLoss: "500000",
      isFormApproved: "No",
      dateOfApproval: "",
      attachDocument: null,
      nameOfAccount: "LMN Industries",
      dateOfComplaint: "2024-01-15",
      letterReferenceNo: "REF/LET/2024/003",
      dateOfDeclarationFraud: "2024-01-20",
      fraudComplaintResignationNo: "FCR/2024/003",
      dateOfReceipt: "2024-01-17",
      complainantName: "Robert Johnson",
      pin: "110001",
      kycLetter1: "Sent on 2024-01-10",
      kycLetter2: "Sent on 2024-01-17",
      replyReceived: "Pending",
      kycEstablishment: "Under Review",
      kycNo: "KYC345678",
      branchOffice: "Delhi Main Branch",
      zoneNbg: "North Zone",
      officialInvolvement: "Yes",
      allegationDetails: "Violation of RBI lending guidelines",
      modusOperandi: "Sanctioned loans without proper documentation",
      officerName: "Vikram Singh",
      officerPf: "PF11223",
      presentPosting: "Delhi Regional Office",
      proposedCompletionDate: "2024-04-30",
      deptObservation: "Serious compliance issue",
      cvoComments: "Detailed investigation required",
      scopeRows: [{ sno: 1, particulars: "Audit documentation" }],
    },
  ],
};

export const emptyApprovalForm = {
  // Reference section
  refNo: "",
  date: new Date().toISOString().slice(0, 10),
  nameOfAccount: "",
  dateOfComplaint: "",
  typeOfComplaint: "",
  sourceOfComplaint: "",
  letterReferenceNo: "",
  dateOfDeclarationFraud: "",
  fraudComplaintResignationNo: "",
  dateOfReceipt: "",

  // Complainant Details
  complainantName: "",
  address: "",
  email: "",
  mobile: "",
  amountInvolved: "",
  pin: "",

  // KYC Details
  kycLetter1: "",
  kycLetter2: "",
  replyReceived: "",
  kycEstablishment: "",
  kycNo: "",

  // Allegation Details
  branchOffice: "",
  zoneNbg: "",
  officialInvolvement: "",
  allegationDetails: "",
  modusOperandi: "",

  // Official Details (for backward compatibility)
  nameOfOfficial: "",
  designation: "",
  state: "",
  natureOfComplaint: "",
  allegationBrief: "",
  probableLoss: "",

  // Allotment Details
  officerName: "",
  officerPf: "",
  presentPosting: "",
  proposedCompletionDate: "",

  // Comments
  deptObservation: "",
  cvoComments: "",

  // Approval Status
  isFormApproved: "",
  dateOfApproval: "",
  attachDocument: null,

  // Scope Rows
  scopeRows: [
    { sno: 1, particulars: "" },
    { sno: 2, particulars: "" },
    { sno: 3, particulars: "" },
  ],
};

export const approvalFormConfig = {
  sections: [
    {
      id: "reference",
      title: "1. Reference:",
      type: "table",
      fields: [
        {
          label: "Name of Account/Complainant",
          name: "nameOfAccount",
          type: "text",
        },
        {
          label: "Date of Complaint/NPA",
          name: "dateOfComplaint",
          type: "date",
        },
        { label: "Type of complaint", name: "typeOfComplaint", type: "text" },
        {
          label: "Source/received through",
          name: "sourceOfComplaint",
          type: "text",
        },
        {
          label: "Letter reference No & date",
          name: "letterReferenceNo",
          type: "text",
        },
        {
          label: "Date of declaration of Fraud",
          name: "dateOfDeclarationFraud",
          type: "date",
        },
        {
          label: "Fraud/Complaint Resignation No.",
          name: "fraudComplaintResignationNo",
          type: "text",
        },
      ],
    },
    {
      id: "complainantDetails",
      title: "2. Details of complainant / Account",
      type: "complex-table",
      // Layout is handled in renderComplexTableSection
    },
    {
      id: "kyc",
      title: "3. Establishment of KYC",
      type: "table",
      fields: [
        {
          label: "1st Letter sent to Complaint ",
          name: "kycLetter1",
          type: "text",
        },
        {
          label: "2nd Letter sent to Complaint",
          name: "kycLetter2",
          type: "text",
        },
        {
          label: "Date of receipt of reply ",
          name: "replyReceived",
          type: "date",
        },
        {
          label: "Whether ownership of KYC established ",
          name: "kycEstablishment",
          type: "text",
        },
        { label: "KYC No (OVD details)", name: "kycNo", type: "text" },
      ],
    },
    {
      id: "allegation",
      title: "4. Allegation / Modus operandi",
      type: "complex-table",
      layout: [
        { label: "Branch/Office :", name: "branchOffice", type: "text" },
        { label: "Zone/NBG :", name: "zoneNbg", type: "text" },
        {
          label:
            "Whether involvement of Bank's official reported in Fraud? / Whether complaint made against Bank's official",
          name: "officialInvolvement",
          type: "text",
        },
        {
          label: "If yes, Please provide details",
          name: "allegationDetails",
          type: "textarea",
          multiline: true,
          colSpan: 3,
        },
        {
          label: "Allegation made/ Modus operandi",
          name: "modusOperandi",
          type: "textarea",
          multiline: true,
          colSpan: 3,
        },
      ],
    },
    {
      id: "scope",
      title: "5. Scope of Investigation",
      type: "dynamic-table",
      fields: [
        { label: "S.No", name: "sno", type: "number", width: 80 },
        {
          label: "Particulars",
          name: "particulars",
          type: "textarea",
          width: "auto",
        },
      ],
    },
    {
      id: "allotment",
      title: "6. Allotment and timeline of investigation",
      type: "complex-table",
      layout: [
        {
          label: "Name of Officer & PF No",
          name: "officerDetails",
          type: "compound",
          fields: [
            { name: "officerName", placeholder: "Name", type: "text" },
            { name: "officerPf", placeholder: "PF No", type: "text" },
          ],
        },
        { label: "Designation", name: "designation", type: "text" },
        { label: "Present Posting", name: "presentPosting", type: "text" },
        {
          label: "Proposed date for completion of investigation",
          name: "proposedCompletionDate",
          type: "date",
        },
      ],
    },
    {
      id: "deptObservation",
      title: "7. Department Observation",
      type: "textarea",
      name: "deptObservation",
    },
    {
      id: "cvoComments",
      title:
        "8. Comments / advise / instruction of the Chief Vigilance Officer",
      type: "textarea",
      name: "cvoComments",
    },
  ],
};
