export const COMPLAINT_STATUS_OPTS = [
  "All Statuses",
  "Pending",
  "Approved",
  "Rejected",
  "Under Review",
];

export const COMPLAINT_TYPE_OPTS = [
  "All Types",
  "Fraud",
  "Misconduct",
  "NPA",
  "Others",
];

export const mockComplaintList = [
  {
    id: "1",
    complaintNumber: "CMP/2024/001",
    fraudReported: "Yes",
    personType: "Individual",
    typeOfFraud: "Loan Fraud",
    dateOfComplaint: "2024-01-15",
    status: "Pending",
    amountInCrore: "5.2",
  },
  {
    id: "2",
    complaintNumber: "CMP/2024/002",
    fraudReported: "No",
    personType: "Corporate",
    typeOfFraud: "NPA",
    dateOfComplaint: "2024-01-10",
    status: "Approved",
    amountInCrore: "12.5",
  },
  {
    id: "3",
    complaintNumber: "CMP/2024/003",
    fraudReported: "Yes",
    personType: "Trust",
    typeOfFraud: "Misappropriation",
    dateOfComplaint: "2024-01-18",
    status: "Under Review",
    amountInCrore: "2.8",
  },
];

export const complaintFormOptionsMap = {
  YesNoOptions: ["Yes", "No"],
  PersonTypeOptions: ["Employee", "Customer", "Both"],
  TypeOfFraudOptions: ["Loan Fraud", "Misappropriation", "NPA", "Others"],
  AgencyOptions: [
    "CBI",
    "Police",
    "Lokpal",
    "DFS",
    "Ministry of Finance",
    "CVC",
  ],
  IncidentOptions: ["FGMO", "ZONE", "Branch", "Others"],
  FGMOptions: ["FGMO North", "FGMO South", "FGMO East", "FGMO West"],
  ZoneOptions: [
    "North Zone",
    "South Zone",
    "East Zone",
    "West Zone",
    "Central Zone",
  ],
  BranchOptions: ["Branch 1", "Branch 2", "Branch 3", "Branch 4", "Branch 5"],
  SourceOfComplaintOptions: [
    "FRMD",
    "CVC",
    "CVO",
    "CBI",
    "DFS",
    "Lokpal",
    "RBI",
    "Ministry",
    "VIP",
    "Other",
  ],
  NatureOfComplaintOptions: [
    "ASL - Audit Special Letter",
    "BRC - Bribery And Corruption",
    "FRD - Fraud",
    "OTH - Others",
    "SAR - Staff Accountability Report",
    "SOR - Special Observation Report",
  ],
  AccountTypeOptions: ["Savings", "Current", "Fixed Deposit", "Loan Account"],
  ComplaintReceivedAtOptions: [
    "BR - Branch",
    "CMDS - CMD's Secretariat",
    "EDS - ED's Secretariat",
    "HO - Head Office",
    "NBG - National Banking",
    "VIGD - Vigilance Dept",
    "ZO - Zonal Office",
  ],
  ComplaintTypeOptions: ["Signed", "Anonymous", "Pseudonymous"],
  FIRRegisteredOptions: ["Yes", "No"],
  ABBBFFOptions: ["Yes", "No"],
};

// Template generators
export const getBranchTemplate = () => ({ id: Date.now(), branchName: "" });
export const getZoneTemplate = () => ({
  id: Date.now(),
  zoneName: "",
  branches: [getBranchTemplate()],
});
export const getFGMOTemplate = () => ({
  id: Date.now(),
  fgmoName: "",
  zones: [getZoneTemplate()],
});

export const getOtherAgenciesTemplate = () => ({
  id: Date.now(),
  selectAgency: "",
  refNo: "",
  dateOfComplaint: null,
  dateOfReceipt: null,
  attachment: null,
  incidentOccurredAt: "",
  remarksInCaseOfOthers: "",
  fgmoName: "",
  zoneName: "",
  branchName: "",
  multipleBranchesUnderSameZone: "",
  branches: [getBranchTemplate()],
  multipleZonesUnderSameFGMO: "",
  zones: [getZoneTemplate()],
  multipleFGMOS: "",
  fgmos: [getFGMOTemplate()],
  sourceOfComplaint: "",
  complaintRefNo: "",
  dateOfComplaintRef: null,
  natureOfComplaint: "",
});

export const getAccountTemplate = () => ({
  id: Date.now(),
  accountName: "",
  accountType: "",
});
export const getComplainantTemplate = () => ({
  id: Date.now(),
  complainantName: "",
  complaintType: "",
  accounts: [getAccountTemplate()],
});

export const emptyComplaintForm = {
  complaintNumber: "",
  fraudReported: "",
  complaintId: "",
  personType: "",
  typeOfFraud: null,
  rbiReferenceNumber: "",
  date1: null,
  date2: null,
  date3: null,
  date4: null,
  date5: null,
  amountInCrore: "",
  consortiumMBA: "",
  leadBankHolder: "",
  complaintFileWithCBI: "",
  dateOfComplaint: null,
  cbiBranch: "",
  place: "",
  firRegistered: "",
  firrcNumber: "",
  date: null,
  attachment: null,
  whetherEligibleABBBFF: "",
  whetherCaseReferredToABBFF: "",
  whetherABBFFAdviceReceived: "",
  whetherSameComplaintReceived: "",
  otherAgenciesList: [getOtherAgenciesTemplate()],
  complainantsList: [getComplainantTemplate()],
  complaintReceivedAt: "",
  descriptionOfComplaint: "",
  actualComplaintDate: null,
  complaintReceivedDateAtHO: null,
  isApproved: "",
  approvalComments: "",
};

// Agency fields configuration
const agencyFields = [
  {
    label: "Select Agency",
    name: "selectAgency",
    type: "select",
    required: true,
    optionsKey: "AgencyOptions",
  },
  { label: "Ref No.", name: "refNo", type: "text", required: true },
  {
    label: "Date of Complaint",
    name: "dateOfComplaint",
    type: "date",
    required: true,
  },
  {
    label: "Date of Receipt",
    name: "dateOfReceipt",
    type: "date",
    required: true,
  },
  { label: "Attachment", name: "attachment", type: "file", required: true },
  {
    label: "Incident Occurred at",
    name: "incidentOccurredAt",
    type: "select",
    required: true,
    optionsKey: "IncidentOptions",
  },
  {
    label: "Remarks",
    name: "remarksInCaseOfOthers",
    type: "text",
    required: true,
    condition: (a) => a.incidentOccurredAt === "Others",
  },
  {
    label: "FGMO Name",
    name: "fgmoName",
    type: "select",
    required: true,
    optionsKey: "FGMOptions",
    condition: (a) => a.incidentOccurredAt === "FGMO",
  },
  {
    label: "Zone Name",
    name: "zoneName",
    type: "select",
    required: true,
    optionsKey: "ZoneOptions",
    condition: (a) => a.incidentOccurredAt === "ZONE",
  },
  {
    label: "Branch Name",
    name: "branchName",
    type: "select",
    required: true,
    optionsKey: "BranchOptions",
    condition: (a) => a.incidentOccurredAt === "Branch",
  },
  {
    label: "Whether Incident Occurred at multiple Branches under same Zone ?",
    name: "multipleBranchesUnderSameZone",
    type: "radio",
    optionsKey: "YesNoOptions",
    required: true,
  },
  {
    label: "Whether Incident Occurred at multiple Zone under same FGMO ?",
    name: "multipleZonesUnderSameFGMO",
    type: "radio",
    optionsKey: "YesNoOptions",
    required: true,
  },
  {
    label: "Whether Incident Occurred at multiple FGMO's ?",
    name: "multipleFGMOS",
    type: "radio",
    optionsKey: "YesNoOptions",
    required: true,
  },
  {
    label: "Source Of Complaint",
    name: "sourceOfComplaint",
    type: "select",
    required: true,
    optionsKey: "SourceOfComplaintOptions",
  },
  { label: "Complaint/Ref. No", name: "complaintRefNo", type: "text" },
  { label: "Date of Complaint/Ref", name: "dateOfComplaintRef", type: "date" },
  {
    label: "Nature of Complaint",
    name: "natureOfComplaint",
    type: "select",
    required: true,
    optionsKey: "NatureOfComplaintOptions",
  },
];

export const complaintFormConfig = {
  sections: [
    {
      id: "complaintDetails",
      title: "Complaint Details",
      fields: [
        {
          label: "Complaint Number",
          name: "complaintNumber",
          type: "text",
          required: true,
          autoAssign: true,
          readOnly: true,
        },
        {
          label: "Fraud Reported?",
          name: "fraudReported",
          type: "radio",
          optionsKey: "YesNoOptions",
        },
      ],
    },
    {
      id: "fraudDetails",
      title: "Fraud Details",
      condition: (v) => v.fraudReported === "Yes",
      fields: [
        {
          label: "Complaint ID",
          name: "complaintId",
          type: "text",
          required: true,
          autoAssign: true,
          readOnly: true,
        },
        {
          label: "Person Type",
          name: "personType",
          type: "select",
          required: true,
          optionsKey: "PersonTypeOptions",
        },
        {
          label: "Type of Fraud",
          name: "typeOfFraud",
          type: "select",
          required: true,
          optionsKey: "TypeOfFraudOptions",
        },
        {
          label: "RBI Reference No",
          name: "rbiReferenceNumber",
          type: "text",
          required: true,
        },
        { label: "Date 1", name: "date1", type: "date", required: true },
        { label: "Date 2", name: "date2", type: "date", required: true },
        { label: "Date 3", name: "date3", type: "date" },
        { label: "Date 4", name: "date4", type: "date" },
        { label: "Date 5", name: "date5", type: "date" },
        {
          label: "Amount (Crore)",
          name: "amountInCrore",
          type: "text",
          required: true,
        },
        {
          label: "Consortium/MBA",
          name: "consortiumMBA",
          type: "select",
          required: true,
          optionsKey: "YesNoOptions",
        },
        {
          label: "Lead Bank/Share Holder",
          name: "leadBankHolder",
          type: "text",
          required: true,
          condition: (v) => v.consortiumMBA === "Yes",
        },
        {
          label: "Complaint with CBI",
          name: "complaintFileWithCBI",
          type: "select",
          required: true,
          optionsKey: "YesNoOptions",
        },
        {
          label: "Date of Complaint",
          name: "dateOfComplaint",
          type: "date",
          required: true,
          condition: (v) => v.complaintFileWithCBI === "Yes",
        },
        {
          label: "CBI Branch",
          name: "cbiBranch",
          type: "text",
          required: true,
          condition: (v) => v.complaintFileWithCBI === "Yes",
        },
        {
          label: "Place",
          name: "place",
          type: "text",
          required: true,
          condition: (v) => v.complaintFileWithCBI === "Yes",
        },
        {
          label: "FIR Registered",
          name: "firRegistered",
          type: "select",
          required: true,
          optionsKey: "YesNoOptions",
        },
        {
          label: "FIR/RC Number",
          name: "firrcNumber",
          type: "text",
          required: true,
          condition: (v) => v.firRegistered === "Yes",
        },
        {
          label: "Date",
          name: "date",
          type: "date",
          required: true,
          condition: (v) => v.firRegistered === "Yes",
        },
        {
          label: "Attachment",
          name: "attachment",
          type: "file",
          condition: (v) => v.firRegistered === "Yes",
          required: false,
        },
        {
          label: "Eligible for ABBFF?",
          name: "whetherEligibleABBBFF",
          type: "select",
          required: true,
          optionsKey: "YesNoOptions",
        },
        {
          label: "Referred to ABBFF",
          name: "whetherCaseReferredToABBFF",
          type: "select",
          optionsKey: "YesNoOptions",
          condition: (v) => v.whetherEligibleABBBFF === "Yes",
        },
        {
          label: "ABBFF Advice Received",
          name: "whetherABBFFAdviceReceived",
          type: "select",
          optionsKey: "YesNoOptions",
          condition: (v) => v.whetherEligibleABBBFF === "Yes",
        },
        {
          label: "Same Complaint from Other Agencies?",
          name: "whetherSameComplaintReceived",
          type: "radio",
          optionsKey: "YesNoOptions",
        },
      ],
    },
    {
      id: "complaintReceived",
      title: "Complaint Received Details",
      fields: [
        {
          label: "Complaint Received At",
          name: "complaintReceivedAt",
          type: "select",
          required: true,
          optionsKey: "ComplaintReceivedAtOptions",
        },
        {
          label: "Description",
          name: "descriptionOfComplaint",
          type: "textarea",
        },
        {
          label: "Actual Complaint Date",
          name: "actualComplaintDate",
          type: "date",
        },
        {
          label: "Received Date at HO",
          name: "complaintReceivedDateAtHO",
          type: "date",
          required: true,
        },
      ],
    },
    {
      id: "doCheckerApproval",
      title: "Approval",
      type: "approval",
      fields: [
        {
          label: "Is Approve",
          name: "isApproved",
          type: "radio",
          required: true,
          options: ["Approve", "Revert"],
        },
        {
          label: "Comments",
          name: "approvalComments",
          type: "textarea",
          condition: (v) => v.isApproved === "Revert",
        },
      ],
    },
  ],
  agencyFields,
};
